version: '2.1'
services:
  db:
    container_name: db
    build: ./db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  service:
    container_name: service
    build: ./
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5000:5000 # expose ports - HOST:CONTAINER
    environment:
    - APP_SETTINGS=project.config.DevelopmentConfig
    - DATABASE_URL=postgres://postgres:postgres@db:5432/path_count
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
